CREATE TABLE AUDIO_FILES(
  filename VARCHAR(1000),
  timestamp VARCHAR(1000),
  PHONE_NUMBER VARCHAR(1000),
  TRANSCRIPTION_PATH VARCHAR(1000), --PATH to gcc bucket
  TRANSLATION_PATH VARCHAR(1000)    --PATH to gcc bucket
)