# Generated by Django 2.2.6 on 2019-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000)),
                ('timestamp', models.CharField(max_length=1000)),
                ('phonenumber', models.CharField(max_length=1000)),
                ('transcription', models.CharField(max_length=1000)),
                ('translation', models.CharField(max_length=1000)),
            ],
        ),
    ]
